name: Tests

on: [push]

jobs:
    build-and-test:
        name: Run Unit Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install node dependencies
              run: npm install
            - name: Test
              run: npm run test
